### ISSUE TITLE
Adapt to VGA

### ISSUE THREAD

**Issue by tinspin** [fhoedemakers/pico-infonesPlus#11]
Could this be adapted to the VGA board:

https://shop.pimoroni.com/products/pimoroni-pico-vga-demo-base

**Comment by fhoedemakers** [comment]
I don't have the board myself. The graphics side  could be made working i guess.  Concerning audio  however,  this has to go through the DAC to the headphone jack and must be coded. The emulator takes up almost the whole memory and it will be a challenge to fit the additional audio processing into it.

**Comment by tinspin** [comment]
Ah, true. I bought the HDMI board... will try to make it work with a USB - I2C NES controller.

Why can't you use the board USB power instead of the Pico USB?

**Comment by fhoedemakers** [comment]
No the board usb power of the pimoroni dvi can be used without a problem.

**Comment by fhoedemakers** [comment]
I was not aware this product existed. 

For a few weeks now, i'm experimenting to get it to work on a small LCD display ( Pimoroni Pico Display Pack 2). It  works and is playable, but the framerate is too slow.  The display cannot display the frames fast enough. I maybe have to use a smaller display  than this 320x240 one i have on hand.  
Also audio is still missing. I will try the Pico audio pack for this. Eventually, all this can be later adapted for use on the Pico System Handheld. But still a lot of hurdles to be taken.

![picodisplay2](https://user-images.githubusercontent.com/8100740/222876413-fbdcecad-983b-46ba-8d2d-50d007d772ed.jpeg)

**Comment by tinspin** [comment]
Are you using both cores? If you move the screen framebuffer handling (and sound later) to the other core and overclock it?

**Comment by fhoedemakers** [comment]
Yes the second core is used for screen updates. As far as i can tell, it is the display that just isn't fast enough and is the bottleneck here. So overclocking the cpu will not work. But i can be wrong, i'll still have to learn a lot.

**Comment by fhoedemakers** [comment]
Closing this one, for Pico System see  [#12 ]

**Comment by dglaude** [comment]
About the frame rate, I believe the limitation might be the SPI connection that is a limiting factor for the FPS.
One way to increase the FPS is to do partial optimized screen update, but that require keeping the previous frame and compare, but it has a cost and not always possible.
Another way is to use screen with parallel connection, that require more pins to connect, you can see that on Adafruit PyPortal.

**Comment by fhoedemakers** [comment]
@tinspin @dglaude Early release for the PicoSystem can be found here: https://github.com/fhoedemakers/PicoSystem_InfoNes
Unfortunately no sound in this release. Feedback appreaciated. :-)
