### ISSUE TITLE
Would it be possible to port to picosystem?

### ISSUE THREAD

**Issue by kefabean** [fhoedemakers/pico-infonesPlus#12]
I would curious to understand whether it would be possible to port to pimoroni picosystem? would this even be feasible?

**Comment by fhoedemakers** [comment]
I think it can be done. 

I'v already been working to get the emulator work on a similar display (Pico Display pack 2). Still work in progress, no sound, framerate too low.  Concerning the Pico System, it has no SD card, but 16MB flash. So there has to be a user friendly way to flash the system with roms. Maybe some kind of companion app for PC with a GUI. Also i'm not sure about the sound capabilities of the Pico System.



![picodisplay2](https://user-images.githubusercontent.com/8100740/222948917-85060cb2-b2b5-4f3f-9c83-94b1b7df9f5c.jpeg)

**Comment by kefabean** [comment]
This looks amazing. Awesome work.I’m not sure I can be much use solving any thorny issues, but as my kids have a couple of picosystems, if there’s anything I can do to compile, test for picosystem let me know.

**Comment by fhoedemakers** [comment]
Work in progress. See [here](https://twitter.com/frenskefrens/status/1637156593946046465?s=46&t=eco_RMZT-2pTUZjTmeRpNw)

**Comment by fhoedemakers** [comment]
@kefabean Early release for the PicoSystem can be found here: https://github.com/fhoedemakers/PicoSystem_InfoNes
Unfortunately no sound in this release. Feedback appreaciated. :-)
![PicoSystem](https://user-images.githubusercontent.com/8100740/226177384-541b9400-f097-4227-80ab-7d4af5bfacb3.jpg)

**Comment by kefabean** [comment]
So cool, thanks! will definitely give it a try and report back. Btw is it relatively straightforward to compile from source in case there’s a way I’m able to contribute?

**Comment by fhoedemakers** [comment]
Yes should compile without any issues. Just let me know if you have any problems so I can help you out.

**Comment by fhoedemakers** [comment]
Closed because project is ported to PicoSystem
