### ISSUE TITLE
SD card mount error: 3

### ISSUE THREAD

**Issue by OldMate6288** [fhoedemakers/pico-infonesPlus#31]
Hi! I got a few of your PCBs made and put it together with the recommended components. Everything seems to be working but I keep getting mount error: 3 on boot. I am using a 16gb SDHC card (FAT32), also tried using a 64gb SDXC card (formatted FAT32 with GUIformat and tried making a 1gb partition but that threw mount error: 1). Looked through the main code too but I couldn't find what the error codes were. 

I am stuck as to what the issue is, my soldering seems to be fine but I will attach pics of everything if you want to double check.

![16gb](https://github.com/fhoedemakers/pico-infonesPlus/assets/93004427/3523fa18-f582-43d7-ac4d-005eb4f3f266)
![64gb](https://github.com/fhoedemakers/pico-infonesPlus/assets/93004427/ca0a2535-8744-4557-92eb-5af239996949)
![Back](https://github.com/fhoedemakers/pico-infonesPlus/assets/93004427/53b3fab6-cd08-4a5c-b753-ca8e77f237de)
![Back2](https://github.com/fhoedemakers/pico-infonesPlus/assets/93004427/0b00583b-e173-4958-a389-b56ac94030a0)
![Front](https://github.com/fhoedemakers/pico-infonesPlus/assets/93004427/b0abdfea-c8ae-46cc-bdda-87f522445302)

**Comment by fhoedemakers** [comment]
Hi, 
Sorry to hear it is not working for you. 
Make sure you installed the latest release for this configuration: https://github.com/fhoedemakers/pico-infonesPlus/releases/download/v0.8/piconesPlusAdaFruitDVISD.uf2 
Also i had issues using cheap SD cards. Make sure you use a card from a well known brand.
Can you also redo the soldering of the SD breakout at the back of the board? Looks like the D1 pin is not fully soldered.


Hope this helps.

Frank

**Comment by OldMate6288** [comment]
Thank you! Turns out it was my soldering, must've missed that pin the first time 🤦

Sorry to open an issue just for this, will be more careful in future.

**Comment by fhoedemakers** [comment]
No problem, glad it works! Enjoy!
