### ISSUE TITLE
Is SPI video and directly wired buttons for a controller possible?

### ISSUE THREAD

**Issue by DormantDrakaiNa** [fhoedemakers/pico-infonesPlus#33]
Is it possible to use an SPI LCD for the video, like a Waveshare display instead of HDMI? And because of a SPI display using a 4 wire interface, is it possible to remove the need for an external controller and hard wire switches to the Pico to be used as a controller?

I'm trying to learn how to do this myself, so apologies if these are dumb questions.

**Comment by fhoedemakers** [comment]
Hi,

Thank you for your question. 

Maybe you can take a  look to my other project [https://github.com/fhoedemakers/PicoSystem_InfoNes](https://github.com/fhoedemakers/PicoSystem_InfoNes).  It is a port of the emulator for the [Pimoroni PicoSystem](https://shop.pimoroni.com/products/picosystem?variant=32369546985555).

The PicoSystem is a handheld device which uses a ST7789 display and has hardwired switches for buttons. This could be a starting point for your project.

Let me know if this helps.

Thanks.
