### ISSUE TITLE
Add support for Waveshare RP2040-PiZero

### ISSUE THREAD

**Issue by lewilou22** [fhoedemakers/pico-infonesPlus#34]
Hi, 

I have the Waveshare RP2040-PiZero. It has 2 USBC ports, hdmi, SD slot & battery input.

Is there a way to add support for this board ?

TIA

**Comment by dglaude** [comment]
That board is also supported for https://github.com/jfedor2/hid-remapper because of the two USB-C  (one for power and one for USB Host with an adapter)... so I plan to get one.

The mini(?) HDMI is a nice addition that fit emulator, retro-computer, ...

**Comment by fhoedemakers** [comment]
Hi,
Will look into this. and see if it can work.
At the moment i don't have the board at hand.  So it may take a while. 
Frank

**Comment by lewilou22** [comment]
If you need me to test anything with my board just let me know

**Comment by fhoedemakers** [comment]
Hi,

Received the board. 

First try is the vanilla emulator from https://github.com/shuichitakano/pico-infones. This in order to get my troubleshooting right.
The emulator works, with sound and image displayed, but as soon as i plug in a usb controller, the sound stops and you only hear crackling noises.  I attached the .uf2 file as a zip so you can try it yourself. Maybe i have a faulty board.

You need to use picotool to flash a rom to the board:

> picotool load foo.nes -t bin -o 0x10080000

[picones.zip](https://github.com/fhoedemakers/pico-infonesPlus/files/14696875/picones.zip)

Let me know what your results are.

**Comment by lewilou22** [comment]
I will take a look at this when i get chance !

**Comment by fhoedemakers** [comment]
Ok, my bad. I used an outdated DVI driver. Must have known this, beacuse i stumbled into exact the same issue last year. 
Included a zipped uf2 file with working sound for WaveShare RP2040.
[picones.zip](https://github.com/fhoedemakers/pico-infonesPlus/files/14720153/picones.zip)
Up next: Get the SD card working. I'll keep you posted.

Frank

**Comment by fhoedemakers** [comment]
Below a complete working version with menu and sound for  WaveShare RP2040-PiZero
[piconesPlus.zip](https://github.com/fhoedemakers/pico-infonesPlus/files/14722614/piconesPlus.zip)

Only works with usb controller now. Will look into it to get it to work also with the original NES gamepad.

Looking forward to your feedback.

Frank

**Comment by lewilou22** [comment]
Awesome! I am at work right now, but I got a chance to load it before I left, it worked from what I could see! The menu came on and the Rom loading screen appreared

**Comment by dglaude** [comment]
With this version:

> Below a complete working version with menu and sound for WaveShare RP2040-PiZero [piconesPlus.zip](https://github.com/fhoedemakers/pico-infonesPlus/files/14722614/piconesPlus.zip)
(I had nothing with previous version)

I have a video signal out, and it complain about the SD card missing.
(same behavior on my two RP2040-PiZero)
Is this a version were we just put the ROM on an SD card?

Not sure I have a compatible USB joystick around.

**Comment by fhoedemakers** [comment]
> With this version:
> 
> > Below a complete working version with menu and sound for WaveShare RP2040-PiZero [piconesPlus.zip](https://github.com/fhoedemakers/pico-infonesPlus/files/14722614/piconesPlus.zip)
> > (I had nothing with previous version)
> 
> I have a video signal out, and it complain about the SD card missing. (same behavior on my two RP2040-PiZero) Is this a version were we just put the ROM on an SD card?
> 
> Not sure I have a compatible USB joystick around.

Yes. Make sure SD card is FAT32 formatted. Rom files must have the .nes extension. I use a 16GB SD card for testing.

**Comment by lewilou22** [comment]
![253a4dd7-f184-465e-8fef-7ad318471e22](https://github.com/fhoedemakers/pico-infonesPlus/assets/35553004/2fc03553-9c01-43be-9c96-b7ce0f1826b7)


Working with sound and PS4 controller on HDMI

**Comment by fhoedemakers** [comment]
> ![253a4dd7-f184-465e-8fef-7ad318471e22](https://github.com/fhoedemakers/pico-infonesPlus/assets/35553004/2fc03553-9c01-43be-9c96-b7ce0f1826b7)
> 
> 
> 
> 
> 
> Working with sound and PS4 controller on HDMI 

Great! Glad it works.

**Comment by lewilou22** [comment]
Thank you!! :) 

I plan on making a micro NES with 3D NES shell files (https://www.printables.com/model/132150-nes-frontloader-replica-shell) & scaling down to fit the WaveShare RP2040-PiZero :)

**Comment by dglaude** [comment]
> I plan on making a micro NES with 3D NES shell files (https://www.printables.com/model/132150-nes-frontloader-replica-shell) & scaling down to fit the WaveShare RP2040-PiZero :)

Maybe a NES controller shaped best fit the PiZero size (and you find 3D files for that).

PS: I was able to test the last release in this issue, reading the SD card and displaying on HDMI was OK, but I could not make my joystick (PS4) to work. I need a kind of USB OTG cable, with USB-C on one side and USB-A host on the other side.

**Comment by fhoedemakers** [comment]
When using the PS4 or PS5 controller, you need an USB-C Y cable like this [one](https://a.co/d/dVY8X1Z).  With this, you can connect an USB-C power adapter and the controller. I tested this and this worked. (both PS4 and PS5 controllers)

I also do not recommend to power the board from the PIO-USB-C connector.  Instead connect your power supply to the port labelled USB. I had some weird issues when power supply was connected to PIO-USB.

**Comment by fhoedemakers** [comment]
If you are interested: I just released a port for Sega Master System emulator. Still work in process, but it runs decently well.

[https://github.com/fhoedemakers/pico-smsplus](https://github.com/fhoedemakers/pico-smsplus)
