### ISSUE TITLE
Rp2040-zero waveshare board psu

### ISSUE THREAD

**Issue by actraiser30** [fhoedemakers/pico-infonesPlus#40]
Hello 

Probably a dump question but cannot find the answer anywhere 

How do i power the board ??

What usb c port I use to give power??

And how much power I give??

Is 5v 1amp ok??

And last do I need to have this usb c 2x splitter cable to connect a joypad or a USB hub will do also and I can connect the PSU directly to a USB port in a hub like the one in the photo down?

![PER 584363](https://github.com/fhoedemakers/pico-infonesPlus/assets/38106933/8b6ecd2e-f9a6-484a-a6c5-8be68a4ed4f5)

Thanks

**Comment by fhoedemakers** [comment]
Hi,

See image below. An USB hub will not work. If you want to connect a controller, you need the splitter cable [like this one](https://a.co/d/gKXWxHM) so you can connect power and the controller (Note: only Ps4 or Ps5 controllers will work). A normal USB-c phone charger will work, so i think 1amp will work.

![Image](https://raw.githubusercontent.com/fhoedemakers/pico-infonesPlus/main/assets/WaveShareRP2040_1.jpg)

**Comment by actraiser30** [comment]
Thanks a lot

I cannot find this splitter cable locally

And to order it online will take months to arrive 
Can I use the second pio-usb port for the joypad or the keyboard??

Thanks

**Comment by fhoedemakers** [comment]
Keyboard will not work. I tried to implement different types of usb controllers, but only Ps4 and Ps5 seem to work.
I think the USB-PIO can be used for powering the board, but i'm not sure.  You cannot use usb-pio for the controller, controller must be connected to the other usb-c port.

Sorry for that.

**Comment by actraiser30** [comment]
No problem I'm sure you doing the best you can,so I cannot really use it coz I dont have the needed ps4,5 controller,the keyboard will not work,a hub will not work, and the splitter cable is not available. Haha 😆 nevermind

**Comment by actraiser30** [comment]
I have the N8 Everdrive if you know it,it has an FPGA inside and your emulator works exactly like it, it reads the game rom from the card and write it to flash rom.

**Comment by fhoedemakers** [comment]
I'll close the issue now. Let me know if you need more help.
