### ISSUE TITLE
Platted or non-platted holes on PCB

### ISSUE THREAD

**Issue by albank1** [fhoedemakers/pico-infonesPlus#43]
Hi

Love this project. I have had an issue with uploading the zip gerber files  on https://learn.adafruit.com/nes-emulator-for-rp2040-dvi-boards/using-pico-breakouts to PCBWay. 

Their engineers came back with the following:
As shown in attached pics, pls confirm the specified four holes should be produced as plated or non-plated?
If they are plated, do you need us add openings on both sides to expose them?
If they are non-plated, we need cut 0.2mm copper around the holes. Is that acceptable for you?

I have gone with non-plated but not sure if this is right
![W475894ASK36-bottom](https://github.com/fhoedemakers/pico-infonesPlus/assets/58950835/ce941910-0cb6-47c7-b340-312e0efdb286)
![W475894ASK36-top](https://github.com/fhoedemakers/pico-infonesPlus/assets/58950835/a16d93cb-bd0a-470b-9691-21bb818ef427)

Thanks

Alban

**Comment by fhoedemakers** [comment]
Hi Alban,

The 4 points indicate the position of the Pico USB connector. No holes are needed, so non-plated is ok.

Let me know if this answer is sufficient for you, so I or you can close the issue.

Best regards,

Frank

**Comment by albank1** [comment]
Many thanks for the clarification
