### ISSUE TITLE
3D Printed Case for the PicoNES PCB

### ISSUE THREAD

**Issue by DynaMight1124** [fhoedemakers/pico-infonesPlus#44]
Hi

Just incase its useful to anyone else, I designed a NES a inspired case for my PicoNES. I always try to share my models, just because I also use a lot of other peoples models so like to share back as much as I can.

https://www.thingiverse.com/thing:6689537

![PicoNES](https://github.com/fhoedemakers/pico-infonesPlus/assets/18290628/66d1500e-050c-413f-bd7e-91a894edf1e6)

**Comment by fhoedemakers** [comment]
Hi,

Great job. I'll update the README asap with a link to the model and I'll include the picture.

Please allow me some time to do this since I'm recovering from surgery.

Frank
