### ISSUE TITLE
can't see memory card

### ISSUE THREAD

**Issue by Anarhist8BIT** [fhoedemakers/pico-infonesPlus#6]
does not see a card with this board, is it possible to make it work with it?
https://img.joomcdn.net/3a98c1d4841ae8d3a28e5b50fb603785311d8f76_original.jpeg

**Comment by fhoedemakers** [comment]
Can you specify the exact brand and product type of this SD breakout board? I cannot see this on the picture.

**Comment by Anarhist8BIT** [comment]
Interfacing Catalex Micro SD Card Module with Arduino
Catalex Micro SD Card Adaptors

**Comment by fhoedemakers** [comment]
Hi,
This specific breakout board needs 5V as input (VCC). Not sure if it works with 3,3V input. Please try to connect board's VCC to the Pico's VBUS pin (pin 40).  See breadboard image in README file where the HDMI board is connected to the same pin (Red wire going up).
Also use quality branded SD-cards, formatted as FAT32.
Hope this helps.

**Comment by Anarhist8BIT** [comment]
> 
I connected directly 3.3 and 5v did not give any result, I tried different memory cards 128mb, 4gb.  16 GB.  wormat fat32.  did not help

**Comment by fhoedemakers** [comment]
Did you also try another Pico? 

I ordered a Catalex SD card module myself and i will see if i can make it work.

**Comment by Anarhist8BIT** [comment]
Tried 3 different ones, assembled from scratch, tried the same new slot.  didn't work out.

**Comment by fhoedemakers** [comment]
Got it working. Please download [this file ](https://github.com/fhoedemakers/pico-infonesPlus/raw/main/assets/piconesPlusCatalex.uf2). Flash it to your Pico and test.
Make sure the SD card reader is connected to 5V. 3V does not work.
Appreciate your feedback.
Thanks!

![Image](https://github.com/fhoedemakers/pico-infonesPlus/raw/main/assets/catalex.jpg)

**Comment by Anarhist8BIT** [comment]
thanks a lot! you make me happier) everything worked

**Comment by Anarhist8BIT** [comment]
sometimes an error about the map may still appear, sometimes the picture disappears during the game, and sometimes just a red screen.

**Comment by fhoedemakers** [comment]
- From the readme:  Due to the Pico's memory limitations, not all games will work. Games not working will show a "Mapper n is unsupported." (n is a number). For example starting Castlevania III will show the "Mapper 5 is unsupported." message.

- I don't now why the picture sometimes dissapears/goes red.  Do all the games show this behaviour or certain ones? In the latter case, can you provide me some examples?
