### ISSUE TITLE
Case for the Waveshare RP2040-PiZero

### ISSUE THREAD

**Issue by DynaMight1124** [fhoedemakers/pico-infonesPlus#60]
Hi

I've designed a case for the Waveshare RP2040-PiZero. Theres info in the Thingiverse link but you basically need the board, 2x NES Ports, some wires to connect them together and 4x M3 6mm (or 4mm) bolts. Its a little bit of a squeeze for the wiring as it was getting a little out of proportion, not sure if its for the best all the time but I've always tried to keep my models as small as possible to save on print time and plastic.  

Link for the files: https://www.thingiverse.com/thing:6758682

![PXL_20240907_190231514](https://github.com/user-attachments/assets/01ac4de4-7457-4c14-8cdc-2661c7de9aad)

**Comment by fhoedemakers** [comment]
Thank you so much for the design. I've updated the README file with images and the link to your design

**Comment by fhoedemakers** [comment]
I also put a link to your design onto the release page. https://github.com/fhoedemakers/pico-infonesPlus/releases/tag/v0.17

I think it is convenient to put it there. Then all is one one place
