### ISSUE TITLE
Wii Classic Controller / Waveshare RP2040 PiZero Board

### ISSUE THREAD

**Issue by SRDWA** [fhoedemakers/pico-infonesPlus#64]
Hello,
I used the Waveshare RP2040 PiZero board for my setup. I've now noticed that the Wii Classic Controller doesn't work. I connected the Adafruit Wii Nunchuck Brackout Adapter to 3.3V, GND, SCL -> GPIO3 and SDA -> GPIO2. Have I made a connection error? Or is the Wii Classic Controller not supported when using the Waveshare board?

Best regards, Sven

**Comment by fhoedemakers** [comment]
Hi Sven,

The Wii Classic Controller is not natively supported by the Waveshare device, but there is no reason it couldn't be.

Below  a zipped .uf2 file for the Waveshare device I just built, which adds support for the Wii Classic Controller on the specified GPIO ports. Could you please give it a try and provide feedback on whether it works? I cannot test it myself

[piconesPlus.zip](https://github.com/user-attachments/files/16995225/piconesPlus.zip)

If this works, i'll add it to the official release.

Frank

**Comment by SRDWA** [comment]
Hi Frank,
First of all, thank you very much for your quick reply. I am even more grateful to you for the image. The title selection menu and the games work with the Wii Classic Controller and can be operated without any problems.
Would it be too much to ask if you could also provide an image with the pico smsplus? (same problem)

**Comment by fhoedemakers** [comment]
Hi Sven,

Will do this tomorrow. No time anymore today. I'll also make a new release for both emulators with these changes.

Frank

**Comment by SRDWA** [comment]
Thank you !!!!!!!

**Comment by SRDWA** [comment]
Just for information. I use the following cable:
https://www.adafruit.com/product/4397

Here is the connection assignment:

![20240913_182416](https://github.com/user-attachments/assets/d04f33d8-8be7-414b-b215-3b1a10d9ae09)
![20240913_182434](https://github.com/user-attachments/assets/11b4cc7c-23af-4f44-b096-3ba5ac1e162b)

You can use the images for the README.

**Comment by fhoedemakers** [comment]
Thanks, will do. Is that an LCD display on which the waveshare is mounted? Can you share the specs? Looks cool.

**Comment by fhoedemakers** [comment]
Below the smsPlus with wii-classic support:

[waveSharePicoSmsPlus.zip](https://github.com/user-attachments/files/16997083/waveSharePicoSmsPlus.zip)

Let me know if this works.

**Comment by SRDWA** [comment]
The monitor is a generic 7" display for Raspberry Pi's.
https://www.amazon.de/dp/B0D1C4XLNY?ref=ppx_yo2ov_dt_b_fed_asin_title

Unfortunately the image doesn't work. The RP2040 doesn't produce an image. Even pressing the RUN button doesn't change anything.

**Comment by SRDWA** [comment]
Sorry. You should also plug in the HDMI cable.
The image works.

**Comment by fhoedemakers** [comment]
Hi Sven,

I just published new releases for InfoNes and SMSPlus.

I updated the (InfoNES) README with details how to setup and I included your pictures.

Let me know if i missed something.

Frank

**Comment by SRDWA** [comment]
Good morning Frank.
I can only thank you once again for the great support. I hope that both nespi/pico sms projects continue to be well maintained and that they continue to develop. Great work! 👍👍👍
